# Generated by Django 4.0.1 on 2022-02-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('generic', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('CM', 'Centimetre')], max_length=2)),
                ('value', models.FloatField()),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_names', to='measurements.measurename')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='measurements.measure')),
            ],
        ),
    ]
