# Generated by Django 4.0.1 on 2022-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('muscle_group', models.TextField(choices=[('Shoulders - Rotator Cuff', 'Shoulders'), ('Legs - Hamstrings', 'Legs H'), ('Abdominals - Total', 'Abdominals T'), ('Abdominals - Lower', 'Abdominals L'), ('Legs - Quadriceps', 'Legs Q'), ('Biceps', 'Biceps'), ('Shoulders - Delts/Traps', 'Shoulders D'), ('Back - Latissimus Dorsi', 'Back'), ('Abdominals - Upper', 'Abdominals U'), ('Abdominals - Obliques', 'Abdominals O'), ('Back - Lat.Dorsi/Rhomboids', 'Back Lat Rho'), ('Calves - Soleus', 'Calves Sol'), ('Calves - Gastrocnemius', 'Calves Gast'), ('Lower Back - Erector Spinae', 'Lower'), ('Triceps', 'Triceps'), ('Chest - Pectoralis', 'Chest'), ('Not known', 'Not Known')], default='Not known', max_length=255)),
            ],
        ),
    ]
