# Generated by Django 4.0.1 on 2022-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.TextField(choices=[('SHOULDERS', 'Shoulders - Rotator Cuff'), ('LEGS_H', 'Legs - Hamstrings'), ('ABDOMINALS_T', 'Abdominals - Total'), ('ABDOMINALS_L', 'Abdominals - Lower'), ('LEGS_Q', 'Legs - Quadriceps'), ('BICEPS', 'Biceps'), ('SHOULDERS_D', 'Shoulders - Delts/Traps'), ('BACK', 'Back - Latissimus Dorsi'), ('ABDOMINALS_U', 'Abdominals - Upper'), ('ABDOMINALS_O', 'Abdominals - Obliques'), ('BACK_LAT_RHO', 'Back - Lat.Dorsi/Rhomboids'), ('CALVES_SOL', 'Calves - Soleus'), ('CALVES_GAST', 'Calves - Gastrocnemius'), ('LOWER', 'Lower Back - Erector Spinae'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest - Pectoralis'), ('NOT_KNOWN', 'Not known')], default='NOT_KNOWN', max_length=255),
        ),
    ]
