# Generated by Django 4.0.1 on 2022-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('Lower', 'Lower'), ('Upper', 'Upper'), ('Core', 'Core'), ('Not known', 'Not known')], default='Not known', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='joint',
            field=models.CharField(choices=[('M', 'Multi-Joint Exercise'), ('S', 'Single-Joint Exercise'), ('Not known', 'Not known')], default='Not known', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.IntegerField(choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'advanced')], default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='modality',
            field=models.CharField(choices=[('FW', 'Free Weights'), ('Cables', 'Cables'), ('Machine', 'Machine'), ('Not known', 'Not known')], default='Not known', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('SHOULDERS', 'Shoulders - Rotator Cuff'), ('LEGS_H', 'Legs - Hamstrings'), ('ABDOMINALS_T', 'Abdominals - Total'), ('ABDOMINALS_L', 'Abdominals - Lower'), ('LEGS_Q', 'Legs - Quadriceps'), ('BICEPS', 'Biceps'), ('SHOULDERS_D', 'Shoulders - Delts/Traps'), ('BACK', 'Back - Latissimus Dorsi'), ('ABDOMINALS_U', 'Abdominals - Upper'), ('ABDOMINALS_O', 'Abdominals - Obliques'), ('BACK_LAT_RHO', 'Back - Lat.Dorsi/Rhomboids'), ('CALVES_SOL', 'Calves - Soleus'), ('CALVES_GAST', 'Calves - Gastrocnemius'), ('LOWER', 'Lower Back - Erector Spinae'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest - Pectoralis'), ('NOT_KNOWN', 'Not known')], default='NOT_KNOWN', max_length=255),
        ),
    ]
